fn main() {
    // 앱 커맨드를 ACL 매니페스트에 선언한다. 이렇게 해야 캡처 창(외부 원격 origin)이
    // capabilities/capture.json 을 통해 capture_push 를 호출할 수 있다.
    // 매니페스트를 선언하면 모든 앱 커맨드가 ACL 대상이 되므로, 로컬 커맨드도 전부 나열하고
    // capabilities/default.json 에서 allow-* 로 허용해야 한다.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
            "list_environments",
            "save_environment",
            "delete_environment",
            "list_scenarios",
            "save_scenario",
            "delete_scenario",
            "export_scenario",
            "import_scenario",
            "list_runs",
            "list_step_results",
            "run_scenario",
            "cancel_run",
            "start_capture_session",
            "stop_capture_session",
            "capture_session_active",
            "capture_push",
            "ui_record",
            "set_ui_recording",
            "start_ui_replay",
            "ui_replay_step",
            "save_ui_actions",
            "load_ui_actions",
            "save_ui_flow",
            "list_ui_flow_sites",
            "list_ui_flows",
            "list_all_ui_flows",
            "delete_ui_flow",
            "export_ui_flows",
            "import_ui_flows",
            "stop_ui_replay",
            "continue_ui_replay",
            "resume_ui_replay",
            "start_replay_mq",
            "stop_replay_mq",
            "run_wait_event",
            "create_ui_run",
            "save_ui_run_step",
            "finish_ui_run",
            "list_ui_runs",
            "list_ui_run_steps",
            "delete_ui_run",
            "clear_ui_runs",
            "rename_ui_flow",
            "rename_ui_group",
        ])),
    )
    .expect("failed to run tauri-build");
}
